# Generated by Django 3.0.8 on 2020-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200928_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie_name',
            field=models.CharField(max_length=250),
        ),
    ]
