# Generated by Django 3.0.8 on 2020-09-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Ticket'),
        ),
    ]
