# Generated by Django 3.0.8 on 2020-09-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200929_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='users',
        ),
    ]
