# Generated by Django 3.0.8 on 2020-09-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='customer',
        ),
    ]
