# Generated by Django 3.0.8 on 2020-09-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_ticket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
    ]
