# Generated by Django 3.0.8 on 2020-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('subject', models.CharField(default='', max_length=250)),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
